project_name: pglet

builds:
  - id: pglet
    main: cmd/pglet/main.go
    env:
      - CGO_ENABLED=0  
    flags:
      - -tags=release  
    ldflags: >
      -X github.com/pglet/pglet/internal/commands.version={{.Version}}
      -X github.com/pglet/pglet/internal/commands.commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''

    builds:
    - pglet

    image_templates:
    - "pglet/server:latest"
    - "pglet/server:{{ .Version }}"
    - "us.gcr.io/pglet-app/pglet-server:{{ .Version }}"

    skip_push: true
    dockerfile: Dockerfile
    use_buildx: true

    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    #- "--build-arg=FOO={{.Env.Bar}}"
    - "--platform=linux/amd64"

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - id: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip    

release:
  prerelease: auto