project_name: pglet

builds:
  - main: cmd/pglet/main.go
    flags:
      - -tags=release  
    ldflags: >
      -X github.com/pglet/pglet/internal/commands.version={{.Version}}
      -X github.com/pglet/pglet/internal/commands.commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip    

release:
  prerelease: auto